# Generated by Django 4.2.7 on 2025-08-30 20:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instrument_type",
                    models.CharField(
                        choices=[
                            ("STOCK", "Stock"),
                            ("OPTION", "Option"),
                            ("FUTURE", "Future"),
                        ]
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "instruments",
                "ordering": ["symbol"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "order_type",
                    models.CharField(choices=[("SELL", "Sell"), ("BUY", "Buy")]),
                ),
                ("price", models.DecimalField(decimal_places=4, max_digits=12)),
                ("original_quantity", models.PositiveIntegerField()),
                ("remaining_quantity", models.PositiveIntegerField()),
                ("filled_quantity", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("FILLED", "Filled"),
                            ("CANCELLED", "Cancelled"),
                            ("PARTIAL", "Partially Filled"),
                        ],
                        default="ACTIVE",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orderbook.instrument",
                    ),
                ),
            ],
            options={
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_id", models.UUIDField(unique=True, verbose_name=uuid.uuid4)),
                ("quantity", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buy_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buy_trade",
                        to="orderbook.order",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="orderbook.instrument",
                    ),
                ),
                (
                    "sell_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sell_trade",
                        to="orderbook.order",
                    ),
                ),
            ],
            options={
                "db_table": "trades",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="trades_created_0dc0e1_idx"
                    ),
                    models.Index(
                        fields=["instrument", "-created_at"],
                        name="trades_instrum_c6b980_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                condition=models.Q(("remaining_quantity__gt", 0), ("status", "ACTIVE")),
                fields=["instrument", "order_type", "price"],
                name="idx_order_type_price",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                condition=models.Q(("status", "ACTIVE")),
                fields=["instrument", "status"],
                name="idx_instrument_order_status",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["instrument", "-created_at"], name="idx_orders_instrument_time"
            ),
        ),
    ]
