# Generated by Django 4.2.7 on 2025-08-23 17:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "instrument_type",
                    models.CharField(
                        choices=[
                            ("STOCK", "Stock"),
                            ("OPTION", "Option"),
                            ("FUTURE", "Future"),
                            ("FX", "Foreign Exchange"),
                        ],
                        max_length=10,
                    ),
                ),
                ("exchange", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-8"))
                        ],
                    ),
                ),
                ("price", models.DecimalField(decimal_places=4, max_digits=12)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.instrument",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-8"))
                        ],
                    ),
                ),
                ("avg_cost", models.DecimalField(decimal_places=4, max_digits=12)),
                ("current_price", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "side",
                    models.CharField(
                        choices=[("LONG", "Long"), ("SHORT", "Short")],
                        default="LONG",
                        max_length=5,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.instrument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarketData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bid_price", models.DecimalField(decimal_places=4, max_digits=12)),
                ("ask_price", models.DecimalField(decimal_places=4, max_digits=12)),
                ("last_price", models.DecimalField(decimal_places=4, max_digits=12)),
                ("volume", models.BigIntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.instrument",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="instrument",
            index=models.Index(
                fields=["symbol", "exchange"], name="portfolio_i_symbol_642a74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="instrument",
            index=models.Index(
                fields=["instrument_type"], name="portfolio_i_instrum_7de9c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(
                fields=["instrument", "timestamp"],
                name="portfolio_t_instrum_333bc7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(
                fields=["timestamp"], name="portfolio_t_timesta_d7bdcf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(
                fields=["side", "timestamp"], name="portfolio_t_side_28752c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["instrument", "last_updated"],
                name="portfolio_p_instrum_584097_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["last_updated"], name="portfolio_p_last_up_c67780_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="position",
            unique_together={("instrument",)},
        ),
        migrations.AddIndex(
            model_name="marketdata",
            index=models.Index(
                fields=["instrument", "timestamp"],
                name="portfolio_m_instrum_08d370_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="marketdata",
            index=models.Index(
                fields=["timestamp"], name="portfolio_m_timesta_e00c60_idx"
            ),
        ),
    ]
